name: Build Linux

on:
  workflow_dispatch:  # Manual trigger
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential cmake git pkg-config \
          libasound2-dev libjack-jackd2-dev \
          libfreetype-dev libfontconfig1-dev \
          libx11-dev libxext-dev libxinerama-dev \
          libxrandr-dev libxcursor-dev libxcomposite-dev \
          libxrender-dev libglu1-mesa-dev mesa-common-dev
    
    - name: Clone JUCE
      run: |
        git clone --depth 1 --branch 7.0.12 https://github.com/juce-framework/JUCE.git ../JUCE
    
    - name: Build plugin
      run: |
        chmod +x build_linux.sh
        ./build_linux.sh Release
    
    - name: Package artifacts
      run: |
        mkdir -p linux-release
        if [ -d "cmake-build-linux/LoudnessCompensator_artefacts" ]; then
          cp -r cmake-build-linux/LoudnessCompensator_artefacts/* linux-release/
        fi
        
        # Create install script
        cat > linux-release/install.sh << 'EOF'
        #!/bin/bash
        echo "Installing LoudnessCompensator for Linux..."
        mkdir -p ~/.vst3 ~/.lv2 ~/.local/bin
        
        if [ -d "VST3" ]; then
          cp -r VST3/* ~/.vst3/
          echo "✅ VST3 plugin installed"
        fi
        
        if [ -d "LV2" ]; then
          cp -r LV2/* ~/.lv2/
          echo "✅ LV2 plugin installed"
        fi
        
        if [ -f "Standalone/LoudnessCompensator" ]; then
          cp Standalone/LoudnessCompensator ~/.local/bin/
          chmod +x ~/.local/bin/LoudnessCompensator
          echo "✅ Standalone application installed"
        fi
        
        echo "🎵 Installation complete!"
        EOF
        chmod +x linux-release/install.sh
        
        # Create archive
        tar -czf LoudnessCompensator-Linux.tar.gz -C linux-release .
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-build
        path: LoudnessCompensator-Linux.tar.gz
    
    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: LoudnessCompensator-Linux.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}